Repository michaelsanguinete/apresentacao, pull requests merged in 2024-05, with the labels that each got.

#1 Service
  src/main/java/com/example/apresentacao/service/ApresentacaoService.java
Labels: enhancement

#2 Primeiros Endpoints
  src/main/java/com/example/apresentacao/controller/UsuarioController.java
  src/main/java/com/example/apresentacao/dto/UsuarioRequest.java
  src/main/java/com/example/apresentacao/dto/UsuarioResponse.java
  src/main/java/com/example/apresentacao/entity/Usuario.java
  src/main/java/com/example/apresentacao/repository/UsuarioRepository.java
  src/main/java/com/example/apresentacao/service/ApresentacaoService.java
  src/main/java/com/example/apresentacao/service/UsuarioService.java
  src/main/resources/application.properties
Labels: documentation

#3 Melhoria
  src/main/java/com/example/apresentacao/service/ApresentacaoService.java
Labels: bug

#4 PR Claudio
  src/main/java/com/example/apresentacao/controller/UsuarioController.java
Labels: documentation
